# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013 - Line length
MD013:
  line_length: 100
  heading_line_length: 100
  code_block_line_length: 100
  code_blocks: false
  tables: false

# MD033 - Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - img

# MD041 - First line in file should be a top level heading
MD041: false

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true
